/**
 * Storefront colour themes (Admin → Theme). A theme is a full set of the storefront's design
 * tokens; the frontend writes them onto :root, so switching themes recolours the whole customer
 * portal. The admin console keeps its own palette.
 *
 * "lavender-peach" is the storefront's original design (app/globals.css :root) and the default —
 * with it active nothing is overridden, so the site looks exactly as designed.
 */

export const THEME_TOKENS = [
  { key: "primary", label: "Primary (buttons, links)", group: "Brand" },
  { key: "primaryForeground", label: "Text on primary", group: "Brand" },
  { key: "secondary", label: "Secondary accent", group: "Brand" },
  { key: "secondaryForeground", label: "Text on secondary", group: "Brand" },
  { key: "accent", label: "Soft highlight (hover wash)", group: "Brand" },
  { key: "accentForeground", label: "Text on highlight", group: "Brand" },
  { key: "background", label: "Page background", group: "Surfaces" },
  { key: "card", label: "Cards & panels", group: "Surfaces" },
  { key: "muted", label: "Quiet surface", group: "Surfaces" },
  { key: "sand", label: "Image placeholder / tinted band", group: "Surfaces" },
  { key: "blush", label: "Warm panel (newsletter, coupon)", group: "Surfaces" },
  { key: "border", label: "Borders & dividers", group: "Surfaces" },
  { key: "foreground", label: "Body text", group: "Text" },
  { key: "mutedForeground", label: "Secondary text", group: "Text" },
  { key: "ink", label: "Footer / deep overlay", group: "Text" },
  { key: "rose", label: "Sale / badge accent", group: "Highlights" },
  { key: "gold", label: "Ratings & stars", group: "Highlights" },
  { key: "sage", label: "Decorative tint", group: "Highlights" },
] as const;

export type ThemeTokenKey = (typeof THEME_TOKENS)[number]["key"];
export type ThemeColors = Record<ThemeTokenKey, string>;

export interface ThemePreset {
  id: string;
  name: string;
  description: string;
  colors: ThemeColors;
}

export const DEFAULT_THEME_ID = "lavender-peach";

export const THEME_PRESETS: ThemePreset[] = [
  {
    id: "lavender-peach",
    name: "Lavender & Peach",
    description: "The original Suthrayaa look — violet actions, peach highlights, soft lilac surfaces.",
    colors: {
      primary: "#6d4aff",
      primaryForeground: "#ffffff",
      secondary: "#ff9e7a",
      secondaryForeground: "#3a1e14",
      accent: "#efeaff",
      accentForeground: "#4b2fd6",
      background: "#fcfbff",
      card: "#ffffff",
      muted: "#f4f1fb",
      sand: "#f3efff",
      blush: "#ffe6dc",
      border: "#e8e3f5",
      foreground: "#1f1a33",
      mutedForeground: "#6b6680",
      ink: "#1c1642",
      rose: "#e2603f",
      gold: "#f5b544",
      sage: "#b9a8ff",
    },
  },
  {
    id: "rose-blossom",
    name: "Rose Blossom",
    description: "Romantic pinks with a berry accent — lovely for gifting seasons.",
    colors: {
      primary: "#d6336c",
      primaryForeground: "#ffffff",
      secondary: "#f9a8c0",
      secondaryForeground: "#4a1024",
      accent: "#fdeaf1",
      accentForeground: "#a61e4d",
      background: "#fffafc",
      card: "#ffffff",
      muted: "#fbf0f4",
      sand: "#fce8ef",
      blush: "#ffe3ec",
      border: "#f3dbe4",
      foreground: "#2d1520",
      mutedForeground: "#7a5b67",
      ink: "#3b0f24",
      rose: "#c2255c",
      gold: "#f2b544",
      sage: "#f4a9c4",
    },
  },
  {
    id: "ocean-breeze",
    name: "Ocean Breeze",
    description: "Cool teal and sky blues — calm, fresh and airy.",
    colors: {
      primary: "#0e7c86",
      primaryForeground: "#ffffff",
      secondary: "#7cc7d9",
      secondaryForeground: "#0b3440",
      accent: "#e3f4f6",
      accentForeground: "#0b5f68",
      background: "#f8fdfd",
      card: "#ffffff",
      muted: "#eef6f7",
      sand: "#e6f2f4",
      blush: "#fdecdf",
      border: "#d9ecef",
      foreground: "#10292e",
      mutedForeground: "#56717a",
      ink: "#0b2a33",
      rose: "#e8704f",
      gold: "#f2b544",
      sage: "#9fd3dc",
    },
  },
  {
    id: "forest-sage",
    name: "Forest Sage",
    description: "Earthy greens and cream — natural, handmade, grounded.",
    colors: {
      primary: "#2f6b4f",
      primaryForeground: "#ffffff",
      secondary: "#d9a86c",
      secondaryForeground: "#3b2610",
      accent: "#e8f1ea",
      accentForeground: "#24543e",
      background: "#fbfaf5",
      card: "#ffffff",
      muted: "#f1f2ea",
      sand: "#eceee2",
      blush: "#f6ead9",
      border: "#e2e4d8",
      foreground: "#1f2a22",
      mutedForeground: "#667062",
      ink: "#1b3326",
      rose: "#c9643c",
      gold: "#d9a441",
      sage: "#a9c4a8",
    },
  },
  {
    id: "terracotta-earth",
    name: "Terracotta Earth",
    description: "Warm clay, olive and sand — the classic artisan palette.",
    colors: {
      primary: "#c1502e",
      primaryForeground: "#ffffff",
      secondary: "#7c9473",
      secondaryForeground: "#ffffff",
      accent: "#f6e7dc",
      accentForeground: "#9a3c1f",
      background: "#fbf6ee",
      card: "#fffdf9",
      muted: "#f3ece1",
      sand: "#efe5d6",
      blush: "#f7e3d6",
      border: "#eadfce",
      foreground: "#3a2a1f",
      mutedForeground: "#7a6a5c",
      ink: "#3a2a1f",
      rose: "#b5452a",
      gold: "#d8a13b",
      sage: "#a9b89f",
    },
  },
  {
    id: "marigold-festive",
    name: "Marigold Festive",
    description: "Saffron and maroon — made for Diwali, weddings and festive drops.",
    colors: {
      primary: "#b3261e",
      primaryForeground: "#ffffff",
      secondary: "#f59e0b",
      secondaryForeground: "#3b2400",
      accent: "#fff1dc",
      accentForeground: "#8a1c16",
      background: "#fffbf3",
      card: "#ffffff",
      muted: "#fbf1e2",
      sand: "#f8ead3",
      blush: "#ffe7c7",
      border: "#f0e0c6",
      foreground: "#2e1a12",
      mutedForeground: "#7a5d4b",
      ink: "#4a0f0c",
      rose: "#d9480f",
      gold: "#f5a524",
      sage: "#f2c572",
    },
  },
  {
    id: "royal-indigo",
    name: "Royal Indigo",
    description: "Deep indigo with antique gold — elegant and premium.",
    colors: {
      primary: "#3730a3",
      primaryForeground: "#ffffff",
      secondary: "#d4a64a",
      secondaryForeground: "#2d2106",
      accent: "#ebeafb",
      accentForeground: "#312e81",
      background: "#fbfbfe",
      card: "#ffffff",
      muted: "#f1f1f8",
      sand: "#eceaf6",
      blush: "#f7ecd8",
      border: "#e2e1f0",
      foreground: "#1b1a33",
      mutedForeground: "#63627e",
      ink: "#15133d",
      rose: "#c2410c",
      gold: "#d4a64a",
      sage: "#a5a1e8",
    },
  },
  {
    id: "mint-pistachio",
    name: "Mint Pistachio",
    description: "Fresh mint and pistachio with a coral pop — light and summery.",
    colors: {
      primary: "#0b7358",
      primaryForeground: "#ffffff",
      secondary: "#ff8f7a",
      secondaryForeground: "#3d1410",
      accent: "#e1f5ee",
      accentForeground: "#0b6a50",
      background: "#f9fdfb",
      card: "#ffffff",
      muted: "#eef6f2",
      sand: "#e6f3ec",
      blush: "#ffe7e1",
      border: "#d9ebe3",
      foreground: "#132822",
      mutedForeground: "#5b7169",
      ink: "#0d2b23",
      rose: "#e5533d",
      gold: "#f0b43c",
      sage: "#a8dcc6",
    },
  },
  {
    id: "sunset-coral",
    name: "Sunset Coral",
    description: "Glowing coral and apricot — cheerful, warm and welcoming.",
    colors: {
      primary: "#c2412c",
      primaryForeground: "#ffffff",
      secondary: "#ffb561",
      secondaryForeground: "#3d2206",
      accent: "#ffede6",
      accentForeground: "#b23a27",
      background: "#fffaf7",
      card: "#ffffff",
      muted: "#fbf1ec",
      sand: "#fbe9df",
      blush: "#ffe4d6",
      border: "#f3e0d6",
      foreground: "#2e1812",
      mutedForeground: "#7d6057",
      ink: "#3a1611",
      rose: "#c7332a",
      gold: "#f2a93b",
      sage: "#f8b9a4",
    },
  },
  {
    id: "berry-plum",
    name: "Berry Plum",
    description: "Rich plum and mulberry with blush accents — cosy and luxurious.",
    colors: {
      primary: "#7b2d6b",
      primaryForeground: "#ffffff",
      secondary: "#e8a0bf",
      secondaryForeground: "#3e1030",
      accent: "#f5e7f1",
      accentForeground: "#62215a",
      background: "#fdf9fc",
      card: "#ffffff",
      muted: "#f6eef4",
      sand: "#f1e5ee",
      blush: "#fae3ee",
      border: "#ecdde8",
      foreground: "#2b1427",
      mutedForeground: "#735d6e",
      ink: "#2e0f2a",
      rose: "#c2185b",
      gold: "#d9a441",
      sage: "#cfa5c8",
    },
  },
  {
    id: "mocha-latte",
    name: "Mocha Latte",
    description: "Coffee browns and warm cream — calm, cosy and timeless.",
    colors: {
      primary: "#7a4b32",
      primaryForeground: "#ffffff",
      secondary: "#d9b08c",
      secondaryForeground: "#3a2414",
      accent: "#f3e9e1",
      accentForeground: "#5f3824",
      background: "#fcf9f5",
      card: "#ffffff",
      muted: "#f3ede6",
      sand: "#eee4d9",
      blush: "#f5e6da",
      border: "#e7ddd2",
      foreground: "#2a1d15",
      mutedForeground: "#76665b",
      ink: "#2c1c13",
      rose: "#b5532e",
      gold: "#c9973d",
      sage: "#c6ae98",
    },
  },
  {
    id: "lemon-sorbet",
    name: "Lemon Sorbet",
    description: "Sunny yellow with a deep teal anchor — bright and playful.",
    colors: {
      primary: "#0f6e75",
      primaryForeground: "#ffffff",
      secondary: "#f7d154",
      secondaryForeground: "#3b2e00",
      accent: "#fff7d6",
      accentForeground: "#0b555b",
      background: "#fffef8",
      card: "#ffffff",
      muted: "#fbf8ea",
      sand: "#fbf3d5",
      blush: "#fff0c4",
      border: "#efe9cf",
      foreground: "#1f2522",
      mutedForeground: "#686e63",
      ink: "#0c3236",
      rose: "#e0593a",
      gold: "#e6b422",
      sage: "#f2dd87",
    },
  },
  {
    id: "peacock-teal",
    name: "Peacock Teal",
    description: "Peacock teal with saffron and gold — vibrant and traditional.",
    colors: {
      primary: "#00707a",
      primaryForeground: "#ffffff",
      secondary: "#ff9f1c",
      secondaryForeground: "#3a2200",
      accent: "#dff3f2",
      accentForeground: "#005760",
      background: "#f9fcfc",
      card: "#ffffff",
      muted: "#edf5f5",
      sand: "#e3f0ef",
      blush: "#ffebd0",
      border: "#d6e8e8",
      foreground: "#0f2628",
      mutedForeground: "#566d6f",
      ink: "#06343a",
      rose: "#d14d1f",
      gold: "#e8a317",
      sage: "#86c8c4",
    },
  },
  {
    id: "charcoal-minimal",
    name: "Charcoal Minimal",
    description: "Monochrome charcoal with a single coral accent — clean and modern.",
    colors: {
      primary: "#262626",
      primaryForeground: "#ffffff",
      secondary: "#f28b6d",
      secondaryForeground: "#3a150b",
      accent: "#f1f1f1",
      accentForeground: "#1f1f1f",
      background: "#fcfcfc",
      card: "#ffffff",
      muted: "#f3f3f3",
      sand: "#eeeeee",
      blush: "#fbe8e1",
      border: "#e5e5e5",
      foreground: "#171717",
      mutedForeground: "#666666",
      ink: "#171717",
      rose: "#dc5a3c",
      gold: "#e0a830",
      sage: "#c9c9c9",
    },
  },
];

export const THEME_PRESETS_BY_ID = new Map(THEME_PRESETS.map((p) => [p.id, p]));
